//test exception 8
int main(){
	int x;
	int y;
	x=-1;
	y=4;
	return y>>x;
}
