//test exception
int main()
{
    {
        int a = 1/0;
    }

    int a = 0;
    return a;
}
