//test exception 8

int loop() {
  int x = 0;
  while(true) { x = 1;}
  return x;
}

int divZero() {
  return 0 / 0;
}

int failMyWay(int x, int y) {
  return 0;
}

int main() {
  return failMyWay(divZero(),loop());
}
