//test exception

//checks that deferencing raises a runtime exception

int main()
{
  int* p;
  p = NULL;
  return *p;
}
