//test error

fn main() = 2