//test exception

int main() {
  main();
  return 0;
}

