//test exception 8

int main() {
  int x = 1;
  int y = 0;

  return (((x/y)));
}
