//test exception

int main()
{
   int x = 5;
   while(x > 0)
	x = x - 1;
   return 5/x;
}
